blank_issues_enabled: false
contact_links:
  - name: Modrinth
    url: https://modrinth.com/mod/socketmc
    about: Download the SocketMC Mod on Modrinth
  - name: Jenkins
    url: https://ci.codemc.io/job/gmitch215/job/SocketMC/
    about: View the Jenkins builds for SocketMC
  - name: Trello
    url: https://trello.com/b/29CtpNlW/socketmc
    about: View the Trello board for SocketMC