name: Release Project
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    name: Publish to Modrinth
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Upload to Modrinth
        run: ./gradlew clean modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}

  publish-github:
    runs-on: ubuntu-latest
    needs: build
    name: Publish to GitHub Packages
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: |
          ./gradlew clean publish -Purl=https://maven.pkg.github.com/gmitch215/SocketMC -Pusername=${{ secrets.GITHUB_ACTOR }} -Ppassword=${{ secrets.GITHUB_TOKEN }}